services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_healthy
    environment:
      SHAREIT_SERVER_URL: "http://server:9090"
    command: [
      "sh", "-c",
      "echo 'Waiting for server...'; 
      while ! curl -s http://server:9090/actuator/health >/dev/null; do 
        sleep 1; 
      done; 
      echo 'Server is ready! Starting Gateway...'; 
      java -jar /app.jar"
    ]

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/shareit"
      SPRING_DATASOURCE_USERNAME: "dbuser"
      SPRING_DATASOURCE_PASSWORD: "12345"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 20s

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: "dbuser"
      POSTGRES_DB: "shareit"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20